version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fake_review_db
    environment:
      POSTGRES_USER: fake_review_user
      POSTGRES_PASSWORD: fake_review_pass
      POSTGRES_DB: fake_review_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fake_review_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fake_review_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_review_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://fake_review_user:fake_review_pass@postgres:5432/fake_review_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_review_dashboard
    command: streamlit run dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://fake_review_user:fake_review_pass@postgres:5432/fake_review_db
      API_URL: http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - api
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_review_celery
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://fake_review_user:fake_review_pass@postgres:5432/fake_review_db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
