[server]
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0e7afe"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f9fc"
textColor = "#1f2330"
